#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.8.2'
cookbook 'ruby_build', '~> 0.8.0'
cookbook 'ruby_rbenv', :github => 'chef-rbenv/ruby_rbenv'
cookbook 'nginx_passenger', '~> 0.5.7'
cookbook 'mongodb-10gen', '~> 0.4.1'
cookbook 'nodejs', '~> 2.4.2'
